// <auto-generated />
using System;
using DisneyApi.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DisneyApi.AccessData.Migrations
{
    [DbContext(typeof(DisneyApiContext))]
    [Migration("20220401213134_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DisneyApi.Domain.Entities.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2083)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Imagen = "Image here!",
                            Nombre = "Fantasy"
                        },
                        new
                        {
                            GeneroId = 2,
                            Imagen = "Image here!",
                            Nombre = "animation"
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2083)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PeliculaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            Calificacion = 4,
                            FechaCreacion = new DateTime(2004, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 1,
                            Imagen = "Image here!",
                            Titulo = "Mickey, Donald, Goofy: The Three Musketeers"
                        },
                        new
                        {
                            PeliculaId = 2,
                            Calificacion = 5,
                            FechaCreacion = new DateTime(2013, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 2,
                            Imagen = "Image here!",
                            Titulo = "Frozen"
                        },
                        new
                        {
                            PeliculaId = 3,
                            Calificacion = 3,
                            FechaCreacion = new DateTime(1929, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroId = 2,
                            Imagen = "Image here!",
                            Titulo = "The Karnival Kid"
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Personaje", b =>
                {
                    b.Property<int>("PersonajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("PersonajeId");

                    b.ToTable("Personajes");

                    b.HasData(
                        new
                        {
                            PersonajeId = 1,
                            Edad = 94,
                            Historia = "Mickey Mouse is a cartoon character created in 1928 by Walt Disney, and is the mascot of The Walt Disney Company. An anthropomorphic mouse who typically wears red shorts, large yellow shoes, and white gloves, Mickey is one of the world's most recognizable fictional characters",
                            Imagen = "Image here!",
                            Nombre = "Mickey Mouse",
                            Peso = 10
                        },
                        new
                        {
                            PersonajeId = 2,
                            Edad = 94,
                            Historia = "Donald duck is an animated character created by Walt Disney as a foil to Mickey Mouse.[15] Making his screen debut in The Wise Little Hen on June 9, 1934, Donald is characterized as a pompous, showboating duck wearing a sailor suit, cap and a bow tie",
                            Imagen = "Image here!",
                            Nombre = "Minnie Mouse",
                            Peso = 20
                        },
                        new
                        {
                            PersonajeId = 3,
                            Edad = 18,
                            Historia = "Anna of Arendelle is a fictional character who appears in Walt Disney Animation Studios' 53rd animated film Frozen (2013) and its sequel and 58th animated film Frozen II (2019). She is voiced by Kristen Bell as an adult. At the beginning of the film, Livvy Stubenrauch and Katie Lopez provide her speaking and singing voice as a young child, respectively. Agatha Lee Monn portrayed her as a nine-year-old (singing)",
                            Imagen = "Image here!",
                            Nombre = "Anna",
                            Peso = 50
                        },
                        new
                        {
                            PersonajeId = 4,
                            Edad = 21,
                            Historia = "Elsa of Arendelle is a fictional character who appears in Walt Disney Animation Studios' 53rd animated film Frozen (2013) and its sequel and 58th animated film Frozen II (2019). She is voiced mainly by Broadway actress and singer Idina Menzel, with Eva Bella as a young child and by Spencer Ganus as a teenager in Frozen",
                            Imagen = "Image here!",
                            Nombre = "Elsa",
                            Peso = 55
                        },
                        new
                        {
                            PersonajeId = 5,
                            Edad = 89,
                            Historia = "Goofy is an animated character that first appeared in 1932's Mickey's Revue.He  is predominately known for his slapstick style of comedy, and regularly appears alongside his best friends Mickey Mouse and Donald Duck",
                            Imagen = "Image here!",
                            Nombre = "Goofy",
                            Peso = 70
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.PersonajePelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("PersonajeId")
                        .HasColumnType("int");

                    b.HasKey("PeliculaId", "PersonajeId");

                    b.HasIndex("PersonajeId");

                    b.ToTable("PersonajePeliculas");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            PersonajeId = 1
                        },
                        new
                        {
                            PeliculaId = 1,
                            PersonajeId = 2
                        },
                        new
                        {
                            PeliculaId = 2,
                            PersonajeId = 3
                        },
                        new
                        {
                            PeliculaId = 2,
                            PersonajeId = 4
                        },
                        new
                        {
                            PeliculaId = 1,
                            PersonajeId = 5
                        },
                        new
                        {
                            PeliculaId = 3,
                            PersonajeId = 1
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Alkymer@alkemy.com",
                            Password = "1234",
                            RoleId = 1,
                            Username = "Alkymer"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "test@test.com",
                            Password = "test",
                            RoleId = 2,
                            Username = "Test"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "test2@test.com",
                            Password = "test",
                            RoleId = 2,
                            Username = "Test2"
                        });
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Pelicula", b =>
                {
                    b.HasOne("DisneyApi.Domain.Entities.Genero", "Genero")
                        .WithMany("Peliculas")
                        .HasForeignKey("GeneroId")
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.PersonajePelicula", b =>
                {
                    b.HasOne("DisneyApi.Domain.Entities.Pelicula", "Pelicula")
                        .WithMany("PersonajePeliculas")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisneyApi.Domain.Entities.Personaje", "Personaje")
                        .WithMany("PersonajePeliculas")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.User", b =>
                {
                    b.HasOne("DisneyApi.Domain.Entities.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Genero", b =>
                {
                    b.Navigation("Peliculas");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Pelicula", b =>
                {
                    b.Navigation("PersonajePeliculas");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Personaje", b =>
                {
                    b.Navigation("PersonajePeliculas");
                });

            modelBuilder.Entity("DisneyApi.Domain.Entities.Role", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
